use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ZWLicensePlateDiscern_Example' do
  pod 'ZWLicensePlateDiscern'
  pod 'AFNetworking'
  # , :path => '../'

  target 'ZWLicensePlateDiscern_Tests' do
    inherit! :search_paths

    
  end
end
