use_frameworks!

platform :ios, '8.0'

target 'ZWLicensePlateDiscern_Example' do
  pod 'ZWLicensePlateDiscern', :path => '../'

  target 'ZWLicensePlateDiscern_Tests' do
    inherit! :search_paths

    
  end
end
